title: New10k
author: Theonefrom AFar
email: bayron.espinosa@cttech.org
description: > # this means to ignore newlines until "baseurl:"
READ.ME

# social links
twitter_username: corn
github_username:  B4yr0n

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
